name: Build and deploy ASP.Net Core app from /api to Azure Web App - saadbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet from /api
        working-directory: ./api
        run: dotnet build --configuration Release

      - name: Publish with dotnet from /api
        working-directory: ./api
        run: dotnet publish -c Release -o ../publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_764AE73064CA4E46BE2EB03AB1CE9189 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_28E0A1713032473EA995E42CA491D668 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8496B8BA04B2492292C39F16BDC0C2E0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'saadbackend'
          slot-name: 'Production'
          package: .
